### ISSUE TITLE
Arduino Template / Example

### ISSUE THREAD

**Issue by richvim** [vult-dsp/vult#37]
I've written a few VCV Rack plugins with Vult now, I'd like to try running some Vult on an Arduino as a Eurorack module. However, I only see templates/examples for WebAudio, JS, PD and Teensy. Are there any instructions for using Vult on an Arduino (particularly the Nano)?

**Comment by richvim** [comment]
(And, now it's out now, the Raspberry Pi Pico! https://www.raspberrypi.org/products/raspberry-pi-pico/)

**Comment by modlfo** [comment]
Hi @richvim, 

since the Arduinos are not very powerful for audio processing, I don't have a template for them. The Vult generated code can run without issues if you generate it with fixed point arithmetic. I have an example here https://github.com/modlfo/endiran/tree/master/Arduino where I use Vult to write a control system. Since the sampling rate is not very high, it worked great.

If you end up using an Arduino for a project and you want to share the process, this repo has a wiki that you can use.
